### ISSUE TITLE
Alternate YAMLSpecification load classmethod

### ISSUE THREAD

**Issue by ben-bay** [LLNL/maestrowf#197]
It would be useful if `YAMLSpecification` had a class method that accepted yaml in string form (instead of a path to a yaml file), as follows:

```
@classmethod
def load_spec_from_str(cls, string):
    # loads python objects from the yaml string, returns a YAMLSpecification
```

If that method existed, `load_specification` could just call it:
```
@classmethod
def load_specification(cls, path):
    with open(path, "r") as f:
        return YAMLSpecification.load_spec_from_str(f.read())
```

**Comment by FrankD412** [comment]
So, l was looking at loading from a string as specified above. It turns out that the `yaml` module does not have a `loads` variant of their parsing API (in a fashion akin to `json` which has a `load` for stream objects and `loads` for string objects). Considering most libraries will support stream objects (like file pointers) by default, I almost wonder if providing an API that takes in a stream is more flexible than limiting to a string. With the structure mentioned in your post, I would have to initialize a `StringIO` object from the string. If I can just assume a stream object from the start, it makes the API more flexible because it means I don't need to add APIs for all types of classes. At that point, it becomes the responsibility of the caller to conform streams.

@ben-bay, does that sound reasonable? It would mean that instead of me taking the string, you would just initialize the stream on your end and pass it to Maestro.

**Comment by ben-bay** [comment]
@FrankD412 that sounds reasonable indeed. It hadn't occurred to me to use streams, but this does seem like the correct place to use them.

**Comment by FrankD412** [comment]
@ben-bay -- Merged. Feel free to pull from develop and use the feature.
