### ISSUE TITLE
remove requirement for every global parameter to have a label

### ISSUE THREAD

**Issue by crkrenn** [LLNL/maestrowf#199]
I have a yaml workflow with the following global.parameters:

    global.parameters:
        MODEL:
            values: [a,b,c]
            label: r_%%
        PROCS:
            values: [36,36,72]
            label: _
        NODES:
            values: [1,1,2]
            label: _

This works, but the directories are labelled `r_a._._`, `r_b._._`, & `r_c._._`, which is aesthetically unappealing. Making a change is not urgent or required, but it would be nice.

**Comment by FrankD412** [comment]
Generally, I require the `label` entry because it controls how the resulting directories look. I had considered making it so that variables could be hidden, but then I hit the ultimate problem -- Maestro cannot make a reasonable guarantee that the resulting directories would still be unique when excluding hidden variables.

At the end of the day, even if hidden they will still have to be taken into account in the path to verify uniqueness.

**Comment by crkrenn** [comment]
Your choice makes sense, and our use cases will probably have not too many more than 10-20 variables, so the directory names will not be unmanageable.
