### ISSUE TITLE
Passing parameters to maestro

### ISSUE THREAD

**Issue by crkrenn** [LLNL/maestrowf#204]
It would be helpful to be able to override variable settings in a YAML design spec from the command line. 

`maestro run study.yaml -def GLOBALS={path_to_globals}`

I'm happy to adapt to whatever convention you think best, but the goal is to override YAML specs. The messy alternative is to write preprocessors using YAML templates. 

This is could be an intermediate step on the way to https://github.com/LLNL/maestrowf/issues/2 ("decide on a merging scheme"), which as far as I can tell was not implemented.

**Comment by FrankD412** [comment]
You're correct about #2 not being implemented. There's some things that I conceptually flagged the last time, most of it is practice versus principle kind of things as well as expected use cases.

1. This feature breaks the principle that a single specification is a 1:1 mapping of the exact process that was run. `pgen` already kind of blurs this line because a user in theory could generate random parameter values and pretty much anything else (the only strict requirement is that they return a `ParameterGenerator` object).
2. This new file is now new input that needs to be tracked and packaged with a specification (again, `pgen` does muddy this, and we simply just copy it to the meta folder). A study is now not as repeatable as it was because it might depend on a set of globals that isn't in the YAML specification. Parameters are kind of different in this regard, because you could always just copy a specification and explicitly set them, but this one could affect the ability to accurate repeat by pathing to other binaries, etc.
3. Should these globals explicitly overwrite the existing variables? A user now needs to look at two files in order to know what the values are for the resulting study. That means the specification is no longer accurately documenting.

This feature is something I've wrestled with mentally, and I cannot argue its use. One potential way to get around these issues might be to consider the study the base, overlay any new changes over the Specification object that contains the study information, and then write that out. That retains the ability to repeat the study exactly as it had been before, but the end result means you wouldn't know a GLOBALS file was used so you lose visibility into the process of executing the study.

I hate to sound like I'm constantly arguing -- again, this feature would be extremely useful, just wanting to think about implementation so that we don't shoot ourselves in both feet later.

@jsemler -- Any thoughts here?

**Comment by crkrenn** [comment]
Hello Frank,

I appreciate your thoughtfulness in keeping the spec general and clean. It should prevent us from getting into the mess of partly working code that we have now. I also appreciate the value of the spec being standalone.

-Chris

Chris Krenn
Lawrence Livermore National Laboratory
Krenn1@llnl.gov<mailto:Krenn1@llnl.gov>
925-423-8636

**Comment by jsemler** [comment]
@FrankD412, does Maestro write out the arguments passed in for ``maestro run`` when a study is run? Maestro could log the variables being overridden to the metadata directory.

**Comment by FrankD412** [comment]
@jsemler and @crkrenn -- Sorry to go silent on this one for a while, between SC and meetings and the like, this slipped through the cracks. @crkrenn -- Please see #209, I've added to the pgen functionality to have access to the `StudyEnvironment` that Maestro constructs. This means that you could in theory set some sensible defaults, or fix the values, and use the variables in a study to dictate behavior. Please see the examples I've updated in that PR and let me know what you think.

**Comment by crkrenn** [comment]
Thank you Frank! -Chris


Chris Krenn
Lawrence Livermore National Laboratory
Krenn1@llnl.gov<mailto:Krenn1@llnl.gov>
925-423-8636
