### ISSUE TITLE
The restart step output will overwrite the cmd output

### ISSUE THREAD

**Issue by koning** [LLNL/maestrowf#240]
This was found by a merlin user see LLNL/merlin#197

**Comment by FrankD412** [comment]
@koning -- Thanks for reporting the bug. I can see where this happens and was entirely an oversight when I implemented the stdout and stderr forwarding. I noticed that you fixed the issue in Merlin, but that's something that should be back propagated to Maestro. Would you mind porting your fix to Maestro? That makes it so that you don't have to update Merlin when it's fixed here.

**Comment by koning** [comment]
My fix was using the script basename, is there away to get the step subname (cmd, restart) sent into the submit (_execute)?  Maybe the script name is the best to use in the end.

**Comment by FrankD412** [comment]
This is something that can actually be fixed by using the PID of the process in the `LocalScriptAdapter` to make the log name unique. The scheduler adapters generally utilize the scheduler's ability to specify using the job identifier in the header. The goal is that the record class should not have to treat the adapter differently just because it's local -- that should remain as abstracted as possible.

**Comment by FrankD412** [comment]
@koning -- Can you kindly review #241?
