### ISSUE TITLE
time specification problem with sbatch

### ISSUE THREAD

**Issue by crkrenn** [LLNL/maestrowf#260]
@jsemler @FrankD412, 

I'm using `maestro 1.1.7dev0` with the rztopaz machine. Maestro converts times in "HH:MM:SS" or "MM:SS" format into seconds, but msub currently works with units of hours. 

Is this a new problem? Can it be fixed?

PS. msub currently still understands "-t n" where "n" is hours, "-t HH:MM:SS" or "-t MM:SS" formats.

**Comment by FrankD412** [comment]
Hi @crkrenn, Maestro uses the native `sbatch` call to schedule. Do you have a sample? The only time I've seen Maestro convert times to seconds has been when the `walltime` wasn't in quotes. Are you putting those into quotes? Alternatively, it might be worth investigating having Maestro just take seconds and convert it in the adapters themselves so that it's consistent across the board.

**Comment by crkrenn** [comment]
Sorry. maestro and encore are passing times correctly.
