### ISSUE TITLE
Focus, once split, can't be recombined/pared down

### ISSUE THREAD

**Issue by RHaluska** [LLNL/maestrowf#48]
When executing a study step over a list of values, you generate len(list) new .sh files. Following steps in the study also seem to generate len(list) new .sh files. This can be extremely useful for processing in-place, but some sort of way to go back to just one .sh for cleanup/etc. would be handy!

**Comment by FrankD412** [comment]
This bug is a remnant of PR #44 which reworked the parameterized study construction logic. The new logic creates sets for each workflow step such that each step maps to a set of used parameters -- with later steps being the union of the parameters used by the step itself and its parents (recursively builds the set).

However, this implementation does not take into account what the previous implementation had. In the previous logic, if a step was not parameterized it was viewed as a step to be executed from the global workspace of the study. These steps would only appear once and could act as hubs in the constructed ExecutionGraph for global study tasks. The new implementation prioritizes used parameters, which means that if a parent step uses at least one parameter then later steps will be assumed to be parameterized.

The deliverable for this ticket is a solution that allows for these global steps to be defined while maintaining the current functionality that tracks used parameters.

**Comment by dinatale2** [comment]
Having `$(step.workspace)` in a command will create multiple nodes in the execution DAG. If you introduce new notation such as `${step.workspace}` which will expand to a space separated list. If you need to choose a delimiter, you could take it one step further and do something like `${step.workspace:_}` which will expand a steps workspace into an underscore delimited list.

That might be a clean way to collapse back down into a single step.

**Comment by FrankD412** [comment]
Closing. I'll reopen if PR #97 did not correct the issue.
